version: "3.7"
services:
  php:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    ports:
      - '54321:80'      
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - php
    container_name: matt-php56-xdebug

networks:
  php:

volumes:
  data: